---

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ cron_packages }}"

- name: Start/enable daemon
  ansible.builtin.service:
    name: "{{ cron_service }}"
    state: started
    enabled: true
