---

- name: Load variables based on OS type
  ansible.builtin.include_tasks: vars.yml

- name: Install phase
  ansible.builtin.include_tasks: install.yml

- name: Config phase
  ansible.builtin.include_tasks: config.yml
