---

- name: Load variables based on OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - "vars"

- name: Install packages
  ansible.builtin.package:
    name: "{{ cron_packages }}"
    state: present

- name: Start/enable daemon
  ansible.builtin.service:
    name: "{{ cron_service }}"
    state: started
    enabled: true
