---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ln -fs molecule/default/requirements.yml
  ansible-lint
  rm -f requirements.yml
platforms:
  - name: cron-rockylinux8-node1
    image: "docker.io/geerlingguy/docker-rockylinux8-ansible:latest"
    rhsm: False
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: True
    pre_build_image: True
    dockerfile: Dockerfile.rockylinux8.j2
provisioner:
  name: ansible
  env:
    ANSIBLE_PIPELINING: "True"
    ANSIBLE_VERBOSITY: 0
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    group_vars: {"linux": {"ansible_user": "vagrant", "ansible_password": "vagrant"}, "windows": {"ansible_user": "vagrant", "ansible_password": "vagrant", "ansible_become_user": "vagrant", "ansible_become_method": "runas", "ansible_connection": "ssh", "ansible_shell_type": "cmd"}}
    host_vars:
      cron-rockylinux8-node1:
        cron_custom_config:
          - key: TZ
            value: Europe/Helsinki
scenario:
  name: default
verifier:
  name: ansible
